apiVersion: apps/v1
kind: Deployment
metadata:
   name: frontend
   labels:
      app: nginx
      project: roboshop
      service: frontend
      env: dev
spec:
   replicas: 1
   selector:
      matchLabels:
         app: nginx
         project: roboshop
         service: frontend
         env: dev
   template:
      metadata:
         app: nginx
         project: roboshop
         service: frontend
         env: dev
      spec:
         containers:
            - name: nginx
              image: nginx:1.14.2
              ports:
                 - containerPort: 80
              resources:
                 requests:
                    memory: "500Mi"
                    cpu: "200m"
                 limits:
                    memory: "500Mi"
                    cpu: "250m"
              livenessProbe:
                 httpGet:
                    path: /
                    port: 80
                 initialDelaySeconds: 10
                 periodSeconds: 5
              readinessProbe:
                 httpGet:
                    path: /
                    port: 80
                 initialDelaySeconds: 10
                 periodSeconds: 5
---
apiVersion: v1
kind: ServiceAccount
metadata:
   name: frontend
---
apiVersion: v1
kind: Service
metadata:
   name: frontend
   annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "alb"
spec:
   type: LoadBalancer
   selector:
      matchLabels:
         app: nginx
         project: roboshop
         service: frontend
         env: dev
   ports:
      - protocol: TCP
        port: 80
        targetPort: 80
